services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      STAGE: 'local'
      DOMAINS: 'localhost -> http://wordpress:8000'
    volumes:
      - ./data/ssl_certs:/var/lib/https-portal

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: someinapress
      MYSQL_DATABASE: inapress
      MYSQL_USER: inapress
      MYSQL_PASSWORD: inapress

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - "8000:8000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: inapress
      WORDPRESS_DB_PASSWORD: inapress
      WORDPRESS_DB_NAME: inapress
    volumes:
     - ./wordpress:/var/www/html
     - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

volumes:
    db_data:
